### ISSUE TITLE
gpg command generated public key does not works?

### ISSUE THREAD

**Issue by winnie-chaintope** [jerson/flutter-openpgp#11]
i used `gpg --full-generate-key` to generate an rsa-3072 bit key having error 

this is the sample pubkey result generating from open pgp package (this works pefectly fine) but
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: fast-openpgp

xo0EX3Pp9AEEAM2lKlXSGOuB4+p2HnkQe5hYRY+Gu1/kNFzAGnPvgxpKi6TaoJHC
fdU8ZDF1jNdP+CyKI/cBEuhoa+ZSgz/imOfcjHIQvAHsCulqusdXzUzrPhNFOV7h
7fS3Z57C1XUMbIpIBWnu5F6FY8cimu/5A1dSoDyZAFHgldSNt0aCgZxdABEBAAHN
FHRlc3QgPHRlc3RAdGVzdC5jb20+wqgEEwEIABwFAl9z6fQJEHZ8hdIAMBRWAhsD
AhkBAgsHAhUIAAB/IQQAxrmmQ/GOT2DTDuvAhBd9UW3k+ObEmH6U96Omt+fHAhnd
4Jp993XYSotUoJBhcxX253+HcKXYn7BpFZaA5w057rd6A+1zrMlxHGn0rdbDCjdp
nFw+6geV4VR8ELVwhCIxoppZ4tUlTi47yDlLyy6Uyv/I28cgzd1Co8TFUjiNBFbO
jQRfc+n0AQQAqPPR+20ukLJZ5yQjtIRsrIJsl1g85I1WQpSI7Za4S3x5TSn4/mlS
Yqzw167Pw5DQJZ+whnU9OspPmteZXr9JyrRE5QFhTMXZaIftVL5KKNOGYtM6Jc92
qAbVT5K1cXGoN15EuxfVabzqWcX/rTdBoBo+lUyDZ/+whg7IP0xKuo8AEQEAAcKf
BBgBCAATBQJfc+n0CRB2fIXSADAUVgIbDAAA38EEAFTpfR4Xk7w5HITFB4kH4TJC
Pf/bDABShm+/Y7/CUsHJNzimpKDBDaRQ5Vw1BEDAF2ba6zXMRTzrW9z9hh3gFpxk
vGZiOsQfFvpIJuZ1I8TxQgZkxkXtHKbMyFzHy/Jv4AKGlbJfGgxpqrstjUZ7sRit
d2Zd2N4xVJuQg3hrj9PY
=F7Xg
-----END PGP PUBLIC KEY BLOCK-----
```

this is a sample pubkey i generated using the gpg command
reason being i only can retrieve the pubkey from my server
when i use this sample pubkey i generated to encrypt it throws error 
even if i copy from starts from -----BEGIN PGP PUBLIC KEY BLOCK-----
any idea why it throws this error? thanks

```
Unhandled Exception: PlatformException(1, Error Domain=go Code=1 "openpgp: invalid data: first packet was not a public/private key" UserInfo={NSLocalizedDescription=openpgp: invalid data: first packet was not a public/private key}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#3      OpenPGP.encrypt (package:openpgp/openpgp.dart:31:27)
```
```
This is a revocation certificate for the OpenPGP key:

pub   rsa3072 2020-10-02 [S]
      E1E1C39BBBCFE4C18D6C80610F626FFCBEE5A365
uid          winnie (testing) <winnie@test.com>

A revocation certificate is a kind of "kill switch" to publicly
declare that a key shall not anymore be used.  It is not possible
to retract such a revocation certificate once it has been published.

Use it to revoke this key in case of a compromise or loss of
the secret key.  However, if the secret key is still accessible,
it is better to generate a new revocation certificate and give
a reason for the revocation.  For details see the description of
of the gpg command "--generate-revocation" in the GnuPG manual.

To avoid an accidental use of this file, a colon has been inserted
before the 5 dashes below.  Remove this colon with a text editor
before importing and publishing this revocation certificate.

:-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: This is a revocation certificate

iQG2BCABCAAgFiEE4eHDm7vP5MGNbIBhD2Jv/L7lo2UFAl92i44CHQAACgkQD2Jv
/L7lo2WZugv/RFv8ktklJ4aJM+vEETuaZuRmAVGfOI5ta0j2BjZd4vR2Mty1Hol3
42zjfGxrAm9O2LN44GsiD/l6fm4FSpqdXUAIjxQH1Vbl41+rtN+NXVUGOCcjJB1m
sYK4ywJqECMan66OU6z6DvYBL+f1jZ4b9t9hJXK+BXP4BhcEiP5dNJvnDcdVky7O
OKl3eVjl0vVOSU0B54Oj1mNXYN17QY3rNtjS23XTlJNfLpYLUHX4bYyPp50mvqUg
TWHGM3ixycgNnCofeltY+aDNTgaYozdW4gcbC30uf3noflYxpF1eX2S/W7w39ToQ
HCcZsTL2K8YOaJt1HJr6VJcApSnN6bpg8F2gT0WQ3e9PwYGjUDwfeNCy3jj2xHPg
zsuGo4N3KyOiFhAqPHECgQnzmdGxUQkVbao8oW8cvYae5bMITwywSjeGrKit9aw/
cSqbgoD7q0uFkCXwJ0VggJNu6UJxAVEGVyXSTdqbJxE8QAkmvlRcIK0S9BD9/+fJ
GWi0uVKVUb9K
=Uy+2
-----END PGP PUBLIC KEY BLOCK-----

```

**Comment by winnie-chaintope** [comment]
so i found that the pub key from the .rev file i given above is not working 
however pubkey from `gpg -a --export` will works
